config/routes.rb
Rails.application.routes.draw do
  get 'checkout/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  root "pages#home"
  
  get 'pages/about', as: 'about'
  resources :static_pages, only: [:show], param: :title
  get 'checkout', to: 'checkout#index', as: 'checkout'
  resources :cards, only: [:index, :show] do
    member do
      post 'add_to_cart'
      delete 'remove_from_cart'
      patch 'update_cart_item'
    end
    collection do
      get 'search'
    end
  end

  resources :card_sets, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      post 'select'
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/card_set.rb
# app/models/card_set.rb
class CardSet < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :series, presence: true
  has_many :cards, dependent: :destroy

  def self.ransackable_attributes(_auth_object = nil)
    ["created_at", "id", "id_value", "name", "series", "updated_at"]
  end
end

app/controllers/card_sets_controller.rb
# app/controllers/card_sets_controller.rb
class CardSetsController < ApplicationController
  def index
    @card_sets = CardSet.all

    return unless @card_sets.empty?

    flash[:alert] =
      "No card sets available. Please run the seed script to populate the card sets."
  end

  def show
    @card_set = CardSet.find(params[:id])
    @cards = @card_set.cards

    return unless @card_set.nil?

    flash[:alert] = "Failed to fetch the set."
    redirect_to card_sets_path
  end

  def new
    @card_set = CardSet.new
  end

  def create
    @card_set = CardSet.new(card_set_params)
    if @card_set.save
      redirect_to @card_set, notice: "CardSet was successfully created."
    else
      render :new
    end
  end

  def edit
    @card_set = CardSet.find(params[:id])
  end

  def update
    @card_set = CardSet.find(params[:id])
    if @card_set.update(card_set_params)
      redirect_to @card_set, notice: "CardSet was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @card_set = CardSet.find(params[:id])
    @card_set.destroy
    redirect_to card_sets_url, notice: "CardSet was successfully destroyed."
  end

  def select
    selected_id = params[:id]
    redirect_to card_set_path(selected_id) # Redirect to the show page of the selected card set
  end

  private

  def card_set_params
    params.require(:card_set).permit(:name, :series)
  end
end

app/controllers/cardsets_controller.rb
# app/controllers/card_sets_controller.rb
class CardSetsController < ApplicationController
  def index
    api = PokemonTcgApi.new(ENV['POKEMON_TCG_API_KEY'])
    response = api.fetch_sets

    if response.success?
      @card_sets = response['data']
    else
      @card_sets = []
      flash[:alert] = "Failed to fetch the sets from the Pokemon TCG API."
    end
  end

  def show
    api = PokemonTcgApi.new(ENV['POKEMON_TCG_API_KEY'])
    response = api.fetch_set(params[:id])

    if response.success?
      @card_set = response['data']
    else
      @card_set = nil
      flash[:alert] = "Failed to fetch the set from the Pokemon TCG API."
      redirect_to card_sets_path
    end
  end

  def new
    @card_set = CardSet.new
  end

  def create
    @card_set = CardSet.new(card_set_params)
    if @card_set.save
      redirect_to @card_set, notice: 'CardSet was successfully created.'
    else
      render :new
    end
  end

  def edit
    @card_set = CardSet.find(params[:id])
  end

  def update
    @card_set = CardSet.find(params[:id])
    if @card_set.update(card_set_params)
      redirect_to @card_set, notice: 'CardSet was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @card_set = CardSet.find(params[:id])
    @card_set.destroy
    redirect_to card_sets_url, notice: 'CardSet was successfully destroyed.'
  end

  private

  def card_set_params
    params.require(:card_set).permit(:set_name, :set_series)
  end
end

app/helpers/card_sets_helper.rb
module CardSetsHelper
end

app/helpers/cardsets_helper.rb
module CardsetsHelper
end

app/views/card_sets/index.html.erb
<% if @card_set %>
  <h1><%= @card_set['name'] %></h1>

  <h2>Cards in this set:</h2>
  <div class="cards">
    <% @card_set['cards'].each do |card| %>
      <div class="card">
        <h3><%= card['name'] %></h3>
        <% if card['images'] %>
          <%= image_tag card['images']['small'], alt: card['name'] %>
        <% end %>
      </div>
    <% end %>
  </div>
<% else %>
  <p>No card set found.</p>
<% end %>

app/views/card_sets/search.html.erb
<h1>Search Pokémon TCG Card Sets</h1>

<%= form_with url: search_card_sets_path, method: :get, local: true do |form| %>
  <div>
    <%= form.label :query, "Search by keyword:" %>
    <%= form.text_field :query, value: params[:query] %>
  </div>

  <div>
    <%= form.label :category_id, "Select Category:" %>
    <%= form.collection_select :category_id, @categories, :id, :name, prompt: "All Categories" %>
  </div>

  <%= form.submit "Search" %>
<% end %>

<h2>Search Results:</h2>
<div class="card-sets">
  <% @card_sets.each do |set| %>
    <div class="card-set">
      <h3><%= set['name'] %></h3>
      <% if set['images'] %>
        <%= image_tag set['images']['small'], alt: set['name'] %>
      <% end %>
      <p><%= set['description'] %></p>
    </div>
  <% end %>
</div>

app/views/card_sets/show.html.erb
<h2>Cards in this set:</h2>
<div class="cards">
  <% @cards.each do |card| %>
    <div class="card">
      <h3><%= card.name %></h3>
      <% if card.image.attached? %>
        <%= image_tag card.image %>
      <% end %>
    </div>
  <% end %>
</div>