config/routes.rb
Rails.application.routes.draw do
  get 'checkout/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  root "pages#home"
  
  get 'pages/about', as: 'about'
  resources :static_pages, only: [:show], param: :title
  get 'checkout', to: 'checkout#index', as: 'checkout'
  resources :cards, only: [:index, :show] do
    member do
      post 'add_to_cart'
      delete 'remove_from_cart'
      patch 'update_cart_item'
    end
    collection do
      get 'search'
    end
  end

  resources :card_sets, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      post 'select'
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :card_set
  belongs_to :item, optional: true

  has_many :items, dependent: :destroy
  has_many :orders, through: :items

  has_one_attached :image

  validates :name, presence: true, uniqueness: true

  scope :search_by_keyword, lambda { |keyword|
    where("title LIKE ? OR description LIKE ?", "%#{keyword}%", "%#{keyword}%")
  }

  scope :filter_by_category, lambda { |category_id|
    where(card_set_id: category_id) if category_id.present?
  }

  def self.ransackable_attributes(_auth_object = nil)
    # Specify the attributes that should be searchable
    ["name", "rarity", "subtype", "supertype", "created_at", "updated_at", "card_set_id"]
  end

  def self.ransackable_associations(_auth_object = nil)
    ["card_set"] # Add associations you want to allow for searching
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!

  def index
    @cards = Card.all.page(params[:page])
  end

  def show
    @card = Card.find(params[:id])
  end

  def search
    @query = params[:query]
    @card_set_id = params[:card_set_id]
    @cards = Card.all

    if @query.present?
      @cards = @cards.where("name ILIKE ? OR description ILIKE ?", "%#{@query}%", "%#{@query}%")
    end

    return unless @card_set_id.present? && @card_set_id != ""

    @cards = @cards.where(card_set_id: @card_set_id).page(params[:page])
  end

  def add_to_cart
    card = Card.find(params[:id])
    active_order = find_or_create_order(card)
    create_item(card, active_order)

    session[:cart] ||= []
    session[:cart] << card.id unless session[:cart].include?(card.id)

    redirect_to root_path, notice: "Item added to cart."
  end

  def remove_from_cart
    item = Item.find(params[:id])
    item.destroy
    session[:cart].remove_from_cart(item.id)
    redirect_to root_path, notice: "Item removed from cart."
  end

  def update_cart_item
    item = Item.find(params[:id])
    if item.update(quantity: params[:quantity])
      redirect_to root_path, notice: "Item quantity updated successfully."
    else
      redirect_to root_path, alert: "Failed to update item quantity."
    end
  end

  private

  def find_or_create_order(card)
    Order.find_or_create_by(order_status: 1, user_id: current_user.id) do |order|
      order.order_total = card.price
    end
  end

  def create_item(card, order)
    Item.create(
      card_id: card.id,
      order_id: order.id,
      quantity: 1
    )
  end
end

app/views/cards/index.html.erb
<h1>All Cards</h1>

<%= form_with url: search_cards_path, method: :get, local: true do |form| %>
  <div>
    <%= form.label :query, "Search Cards" %>
    <%= form.text_field :query %>
  </div>
  <div>
    <%= form.label :card_set_id, "Select Set" %>
    <%= form.collection_select :card_set_id, CardSet.all, :id, :name, include_blank: "All Sets" %>
  </div>
  <%= form.submit "Search" %>
<% end %>

<details>
  <summary>Shopping Cart</summary>
  <% if @cart.empty? %>
    <p>No items in cart.</p>
  <% else %>
    <ul>
      <% @cart.each do |item| %>
        <li>
          <%= item.card.name %> - Quantity: <%= item.quantity %>
          <%= form_with url: update_cart_item_card_path(item), method: :patch, local: true do |form| %>
            <%= form.number_field :quantity, value: item.quantity, min: 1 %>
            <%= form.submit 'Update Quantity' %>
          <% end %>
          <%= link_to 'Remove from cart', remove_from_cart_card_path(item), data: { 'turbo-method' => :delete } %>
        </li>
      <% end %>
            <li><%= link_to 'Checkout', checkout_path %></li>

    </ul>
  <% end %>
</details>

<% if @cards.any? %>
  <div class="cards">
    <% @cards.each do |card| %>
      <div class="card">
        <h2><%= card.name %></h2>
        
        <% if card.image.attached? %>
          <%= image_tag url_for(card.image), alt: card.name %>
        <% else %>
          <% if card['images'] %>
            <%= image_tag card['images']['small'], alt: card.name %>
          <% end %>
        <% end %>
        
        <p><%= link_to 'Details', card_path(card) %></p>
        <% if @cart.any? { |item| item.card_id == card.id } %>
          <p><%= button_to 'Remove from cart', remove_from_cart_card_path(card), data: { 'turbo-method' => :delete } %></p>
        <% else %>
          <p><%= button_to 'Add to Cart', add_to_cart_card_path(card), data: { 'turbo-method' => :post } %></p>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= paginate @cards %>
<% else %>
  <p>No cards found.</p>
<% end %>

app/views/cards/search.html.erb
<h1>Search Results</h1>

<%= form_with url: search_cards_path, method: :get, local: true do |form| %>
  <%= form.label :query, "Search Cards" %>
  <%= form.text_field :query %>
  <%= form.submit "Search" %>
<% end %>

<% if @cards.any? %>
  <ul>
    <% @cards.each do |card| %>
      <li><%= link_to card.name, card_path(card) %></li>
    <% end %>
  </ul>
<% else %>
  <p>No cards found.</p>
<% end %>

app/views/cards/show.html.erb
<h1><%= @card['name'] %></h1>

<% if @card['images'] %>
  <%= image_tag @card['images']['large'] %>
<% end %>

<p><strong>Supertype:</strong> <%= @card['supertype'] %></p>
<p><strong>Subtypes:</strong> <%= @card['subtype'] %></p>
<p><strong>Set:</strong> <%= @card.card_set.name %></p>
<p><strong>Rarity:</strong> <%= @card['rarity'] %></p>
<p><strong>Price:</strong> $<%= @card['price'] %></p>