config/routes.rb
Rails.application.routes.draw do
  get 'checkout/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  root "pages#home"
  
  get 'pages/about', as: 'about'
  resources :static_pages, only: [:show], param: :title
  get 'checkout', to: 'checkout#index', as: 'checkout'
  resources :cards, only: [:index, :show] do
    member do
      post 'add_to_cart'
      delete 'remove_from_cart'
      patch 'update_cart_item'
    end
    collection do
      get 'search'
    end
  end

  resources :card_sets, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      post 'select'
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/_navigation.html.erb
<nav>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', about_path %></li>
    
    <% if user_signed_in? %>
      <li><%= link_to 'Sign out', destroy_user_session_path, data: { 'turbo-method' => :delete } %></li>
      <li><%= link_to 'Profile', edit_user_registration_path %></li>
      <li><%= link_to 'Admin', admin_root_path %></li>
    <% else %>
      <li><%= link_to 'Register', new_user_registration_path %></li>
      <li><%= link_to 'Login', new_user_session_path %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PokemonStore</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
<h1>Pokemon Cards</h1>
<%= render 'layouts/navigation' %>


<%= form_with url: select_card_sets_path, method: :post, local: true do |form| %>
  <div>
    <%= form.label :id, "Select Set" %>
    <%= form.collection_select :id, CardSet.all, :id, :name, prompt: "Pokémon Sets" %>
    <%= form.submit "Go" %>
  </div>
<% end %>


<%= form_with url: search_cards_path, method: :get, local: true do |form| %>
  <%= form.label :query, "Search Cards" %>
  <%= form.text_field :query %>
  <%= form.submit "Search" %>
<% end %>

<%= yield %>
</body>
</html>